name: "Auto assign maintainer to issue"
on:
  push:
    branches:
      - main

jobs:
  assign-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const assignees = ['mstoykov', 'imiric', 'codebien', 'olegbespalov', 'oleiade'];
            const assigneeCount = 2;
            const crypto = require("node:crypto");

            const r = () => {
              let a = crypto.getRandomBytes(1);
              return a[0]%2 == 0 ? -1: 1;
            }
            console.log(assignees.sort(r).slice(0, assigneeCount))
