name: "Auto assign maintainer to issue"
on:
  push:
    branches:
      - main

jobs:
  assign-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const assignees = ['mstoykov', 'imiric', 'codebien', 'olegbespalov', 'oleiade'];
            const assigneeCount = 2;
            const crypto = require("node:crypto");

            const randomSign = () => {
              return crypto.randomBytes(1)[0]? a[0]%2 == 0 ? -1: 1;
            }

            const getNRandom = (n, array) {
              let result = [];
              while (n > 0) {
                const chosen = array[crypto.randomInt(array.length)];
                result.push(chosen)
                array = array.filter(u => u != chosen);
              }
              return result;
            }
            console.log(getNRandom(assigneeCount, assignees))
